version: '3.8'

services:
  homepage:
    build: .
    container_name: homepage
    restart: always
    ports:
      - "3003:3003"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./public:/app/public
    environment:
      - NODE_ENV=production
      - PORT=3003
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s