name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to the Docker registry
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build and push Docker image
      run: |
        # 假设你的 Dockerfile 在根目录下
        docker build -t ${DOCKER_USERNAME}/homepage .
        docker tag ${DOCKER_USERNAME}/homepage ${DOCKER_USERNAME}/homepage:last
        docker push ${DOCKER_USERNAME}/homepage
