name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout code

    
    - name: Log in to the Docker registry
      run: |
        docker login -u huajiee -p huajie@333

    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag homepage:last
