name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get Latest Release
      id: get_release
      run: |
        response=$(curl -s https://api.github.com/repos/<owner>/<repo>/releases/latest)
        latest_version=$(echo $response | jq -r .tag_name)
        echo "Latest release version: $latest_version"
        echo "::set-output name=latest_version::$latest_version"

    - name: Use Latest Release
      run: |
        echo "The latest release version is ${{ steps.get_release.outputs.latest_version }}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/homepage:${{ steps.get_release.outputs.latest_version }}
    
    - name: Push the Docker image
      run: docker push huajiee/homepage:${{ steps.get_release.outputs.latest_version }}

  create-tag:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    if: github.event_name == 'release'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create tag and push to GitHub
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git tag -a v${GITHUB_REF#refs/tags/v} -m "Version ${GITHUB_REF#refs/tags/v}"
        git push origin --tags
